package store

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"strings"
	"unicode"

	"entmoot/pkg/entmoot"
)

const maxSearchQueryLength = 256

var ErrInvalidSearchQuery = errors.New("store: invalid search query")

// SearchBoundary identifies the exclusive upper edge for older search result
// pagination in the newest-first order used by SearchMessages.
type SearchBoundary struct {
	TimestampMS    int64
	AuthorMemberID entmoot.MemberID
	MessageID      entmoot.MessageID
}

// SearchOptions controls one lexical search page.
type SearchOptions struct {
	Limit          int
	CursorBoundary *SearchBoundary
	Topic          string
}

// SearchHit is one lexical search result. Message is the signed source of
// truth; Snippet is display-only context generated by the search backend.
type SearchHit struct {
	Message entmoot.Message
	Snippet string
}

// SearchResult is one page of lexical search hits.
type SearchResult struct {
	Hits               []SearchHit
	HasMore            bool
	NextCursorBoundary *SearchBoundary
}

// MessageSearcher is implemented by stores with a native search index.
type MessageSearcher interface {
	SearchMessages(ctx context.Context, groupID entmoot.GroupID, query SearchQuery, opts SearchOptions) (SearchResult, error)
}

// SearchMessages searches st using a native search index when available, or a
// deterministic in-process scan for stores that do not maintain an index.
func SearchMessages(ctx context.Context, st MessageSearcher, groupID entmoot.GroupID, query string, opts SearchOptions) (SearchResult, error) {
	normalized, err := NormalizeSearchQuery(query)
	if err != nil {
		return SearchResult{}, err
	}
	opts.Topic = strings.TrimSpace(opts.Topic)
	if opts.Limit <= 0 {
		return SearchResult{Hits: []SearchHit{}}, nil
	}
	return st.SearchMessages(ctx, groupID, normalized, opts)
}

// SearchQuery is the normalized representation shared by scan and indexed
// search paths.
type SearchQuery struct {
	Query string
	Terms []string
	FTS5  string
}

// NormalizeSearchQuery trims, validates, tokenizes, and builds a safe FTS5
// MATCH expression from user text. Raw user input must never be passed directly
// to FTS5 MATCH.
func NormalizeSearchQuery(raw string) (SearchQuery, error) {
	query := strings.TrimSpace(raw)
	if query == "" {
		return SearchQuery{}, fmt.Errorf("%w: empty query", ErrInvalidSearchQuery)
	}
	if len([]rune(query)) > maxSearchQueryLength {
		return SearchQuery{}, fmt.Errorf("%w: query exceeds %d characters", ErrInvalidSearchQuery, maxSearchQueryLength)
	}
	terms := searchTerms(query)
	if len(terms) == 0 {
		return SearchQuery{}, fmt.Errorf("%w: query contains no searchable terms", ErrInvalidSearchQuery)
	}
	ftsTerms := make([]string, 0, len(terms))
	for _, term := range terms {
		ftsTerms = append(ftsTerms, quoteFTS5Term(term))
	}
	return SearchQuery{
		Query: strings.Join(terms, " "),
		Terms: terms,
		FTS5:  strings.Join(ftsTerms, " AND "),
	}, nil
}

func searchTerms(query string) []string {
	seen := make(map[string]struct{})
	var terms []string
	for _, term := range strings.FieldsFunc(query, func(r rune) bool {
		return !(unicode.IsLetter(r) || unicode.IsNumber(r))
	}) {
		term = strings.ToLower(strings.TrimSpace(term))
		if term == "" {
			continue
		}
		if _, ok := seen[term]; ok {
			continue
		}
		seen[term] = struct{}{}
		terms = append(terms, term)
	}
	return terms
}

func quoteFTS5Term(term string) string {
	return `"` + strings.ReplaceAll(term, `"`, `""`) + `"`
}

func searchMessageOlderThan(m entmoot.Message, boundary SearchBoundary) bool {
	if m.Timestamp != boundary.TimestampMS {
		return m.Timestamp < boundary.TimestampMS
	}
	author := messageMemberID(m)
	if author != boundary.AuthorMemberID {
		return bytes.Compare(author[:], boundary.AuthorMemberID[:]) < 0
	}
	return bytes.Compare(m.ID[:], boundary.MessageID[:]) < 0
}

func searchBoundaryFromMessage(m entmoot.Message) SearchBoundary {
	return SearchBoundary{
		TimestampMS:    m.Timestamp,
		AuthorMemberID: messageMemberID(m),
		MessageID:      m.ID,
	}
}
