package store

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"sort"
	"strings"
	"unicode"

	"entmoot/pkg/entmoot"
)

const maxSearchQueryLength = 256

var ErrInvalidSearchQuery = errors.New("store: invalid search query")

// SearchBoundary identifies the exclusive upper edge for older search result
// pagination in the newest-first order used by SearchMessages.
type SearchBoundary struct {
	TimestampMS  int64
	AuthorNodeID entmoot.NodeID
	MessageID    entmoot.MessageID
}

// SearchOptions controls one lexical search page.
type SearchOptions struct {
	Limit          int
	CursorBoundary *SearchBoundary
	Topic          string
}

// SearchHit is one lexical search result. Message is the signed source of
// truth; Snippet is display-only context generated by the search backend.
type SearchHit struct {
	Message entmoot.Message
	Snippet string
}

// SearchResult is one page of lexical search hits.
type SearchResult struct {
	Hits               []SearchHit
	HasMore            bool
	NextCursorBoundary *SearchBoundary
}

// MessageSearcher is implemented by stores with a native search index.
type MessageSearcher interface {
	SearchMessages(ctx context.Context, groupID entmoot.GroupID, query SearchQuery, opts SearchOptions) (SearchResult, error)
}

// SearchMessages searches st using a native search index when available, or a
// deterministic in-process scan for stores that do not maintain an index.
func SearchMessages(ctx context.Context, st MessageStore, groupID entmoot.GroupID, query string, opts SearchOptions) (SearchResult, error) {
	normalized, err := NormalizeSearchQuery(query)
	if err != nil {
		return SearchResult{}, err
	}
	opts.Topic = strings.TrimSpace(opts.Topic)
	if opts.Limit <= 0 {
		return SearchResult{Hits: []SearchHit{}}, nil
	}
	if searcher, ok := st.(MessageSearcher); ok {
		return searcher.SearchMessages(ctx, groupID, normalized, opts)
	}
	return scanSearchMessages(ctx, st, groupID, normalized, opts)
}

// SearchQuery is the normalized representation shared by scan and indexed
// search paths.
type SearchQuery struct {
	Query string
	Terms []string
	FTS5  string
}

// NormalizeSearchQuery trims, validates, tokenizes, and builds a safe FTS5
// MATCH expression from user text. Raw user input must never be passed directly
// to FTS5 MATCH.
func NormalizeSearchQuery(raw string) (SearchQuery, error) {
	query := strings.TrimSpace(raw)
	if query == "" {
		return SearchQuery{}, fmt.Errorf("%w: empty query", ErrInvalidSearchQuery)
	}
	if len([]rune(query)) > maxSearchQueryLength {
		return SearchQuery{}, fmt.Errorf("%w: query exceeds %d characters", ErrInvalidSearchQuery, maxSearchQueryLength)
	}
	terms := searchTerms(query)
	if len(terms) == 0 {
		return SearchQuery{}, fmt.Errorf("%w: query contains no searchable terms", ErrInvalidSearchQuery)
	}
	ftsTerms := make([]string, 0, len(terms))
	for _, term := range terms {
		ftsTerms = append(ftsTerms, quoteFTS5Term(term))
	}
	return SearchQuery{
		Query: strings.Join(terms, " "),
		Terms: terms,
		FTS5:  strings.Join(ftsTerms, " AND "),
	}, nil
}

func searchTerms(query string) []string {
	seen := make(map[string]struct{})
	var terms []string
	for _, term := range strings.FieldsFunc(query, func(r rune) bool {
		return !(unicode.IsLetter(r) || unicode.IsNumber(r))
	}) {
		term = strings.ToLower(strings.TrimSpace(term))
		if term == "" {
			continue
		}
		if _, ok := seen[term]; ok {
			continue
		}
		seen[term] = struct{}{}
		terms = append(terms, term)
	}
	return terms
}

func quoteFTS5Term(term string) string {
	return `"` + strings.ReplaceAll(term, `"`, `""`) + `"`
}

func scanSearchMessages(ctx context.Context, st MessageStore, groupID entmoot.GroupID, query SearchQuery, opts SearchOptions) (SearchResult, error) {
	msgs, err := st.Range(ctx, groupID, 0, 0)
	if err != nil {
		return SearchResult{}, err
	}
	hits := make([]SearchHit, 0, len(msgs))
	for _, msg := range msgs {
		if opts.Topic != "" && !messageHasTopic(msg, opts.Topic) {
			continue
		}
		if opts.CursorBoundary != nil && !searchMessageOlderThan(msg, *opts.CursorBoundary) {
			continue
		}
		if !messageContentMatches(msg, query.Terms) {
			continue
		}
		hits = append(hits, SearchHit{
			Message: msg,
			Snippet: string(msg.Content),
		})
	}
	sortSearchHits(hits)
	result := SearchResult{Hits: hits}
	if len(result.Hits) > opts.Limit {
		result.HasMore = true
		result.Hits = result.Hits[:opts.Limit]
	}
	if result.HasMore && len(result.Hits) > 0 {
		boundary := searchBoundaryFromMessage(result.Hits[len(result.Hits)-1].Message)
		result.NextCursorBoundary = &boundary
	}
	if result.Hits == nil {
		result.Hits = []SearchHit{}
	}
	return result, nil
}

func messageContentMatches(msg entmoot.Message, terms []string) bool {
	contentTerms := searchTerms(string(msg.Content))
	content := make(map[string]struct{}, len(contentTerms))
	for _, term := range contentTerms {
		content[term] = struct{}{}
	}
	for _, term := range terms {
		if _, ok := content[term]; !ok {
			return false
		}
	}
	return true
}

func sortSearchHits(hits []SearchHit) {
	sortSearchMessages(hits, func(i int) entmoot.Message { return hits[i].Message })
}

func sortSearchMessages[T any](items []T, messageAt func(int) entmoot.Message) {
	sort.Slice(items, func(i, j int) bool {
		a := messageAt(i)
		b := messageAt(j)
		if a.Timestamp != b.Timestamp {
			return a.Timestamp > b.Timestamp
		}
		if a.Author.PilotNodeID != b.Author.PilotNodeID {
			return a.Author.PilotNodeID > b.Author.PilotNodeID
		}
		return bytes.Compare(a.ID[:], b.ID[:]) > 0
	})
}

func searchMessageOlderThan(m entmoot.Message, boundary SearchBoundary) bool {
	if m.Timestamp != boundary.TimestampMS {
		return m.Timestamp < boundary.TimestampMS
	}
	if m.Author.PilotNodeID != boundary.AuthorNodeID {
		return m.Author.PilotNodeID < boundary.AuthorNodeID
	}
	return bytes.Compare(m.ID[:], boundary.MessageID[:]) < 0
}

func searchBoundaryFromMessage(m entmoot.Message) SearchBoundary {
	return SearchBoundary{
		TimestampMS:  m.Timestamp,
		AuthorNodeID: m.Author.PilotNodeID,
		MessageID:    m.ID,
	}
}
